name: check_versions
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * 0     # weekly

permissions: {}

jobs:
  check_pytorch_version:
    runs-on: ubuntu-latest
    name: Check api_change.py against plenoptic
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - run: |
        URL=https://raw.githubusercontent.com/plenoptic-org/plenoptic/refs/heads/main/src/plenoptic/_api_change.py
        echo "Downloading _api_change.py from $URL"
        curl $URL > plenoptic_api_change.py
        diff plenoptic_api_change.py src/plenoptic_migrate/api_change.py
